import "./global.css"
import Header from "../components/Hearder"
import Footer from "../components/footer"


export const metadata = {
  title: 'Company Name',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <header>
          <Header/>
        </header>

        <main>
          {children}
        </main>
        
        <footer>
          <Footer />
        </footer>
      </body>
    </html>
  )
}
